name: go-build

on:
  push:
    branches:
      - main
      - feature/*
      - fix/*
      - release/*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        go_os: [linux]
        go_arch: [amd64, arm64]    
    permissions:
      contents: read
    uses: josephrodriguez/github-workflow/.github/workflows/golang-build.yaml@13e779d2fd175211715efbdfb8159d79eb088151
    with:
      go_version: 1.24.10
      go_build_output_name: ${{ github.event.repository.name }}
      go_build_output_dir: 'dist/${{ matrix.go_os }}/${{ matrix.go_arch }}'
      go_build_ldflags: '-s -w -X main.Version=${{ github.ref_name }}'
      go_build_gcflags: 'all=-trimpath=${PWD}'
      go_build_os: ${{ matrix.go_os }}
      go_build_arch: ${{ matrix.go_arch }}
      go_coverage_enabled: true
      go_coverage_threshold: 0
      go_lint_enabled: false
      go_artifacts_enabled: true
      go_artifacts_name: '${{ github.event.repository.name }}_${{ matrix.go_os }}_${{ matrix.go_arch }}.tar.gz'
      sonar_analysis_enabled: true
      sonar_cache_enabled: true
      sonar_project_key: 'josephrodriguez_gotter'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dependabot:
    needs: [build]
    permissions: write-all
    uses: josephrodriguez/github-workflow/.github/workflows/dependabot-merge-pull-request.yaml@13e779d2fd175211715efbdfb8159d79eb088151
    secrets:
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}         